language: node_js
node_js:
  - "8"
env:
  - CODACY_PROJECT_TOKEN=e0aa13ef56504b8eb5d159b9117b45f0
before_script:
  - npm install -g eslint
  - sudo apt-get install jq
  - curl -LSs "$(curl -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | endswith(".jar"))) | .[0].browser_download_url')" -o codacy-coverage-reporter-assembly.jar
  #- npm install -g karma
script: true
  #- npm run build
  #- npm run test
  #- npm run lint
after_success:
  - ls
  - find / -name lcov.info
  - java -jar codacy-coverage-reporter-assembly.jar report -l Javascript -r ./lcov.info